# Generated by Django 4.2.17 on 2024-12-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipe_thumbs_down_recipe_thumbs_up_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='thumbs_up',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
