# Generated by Django 4.2.17 on 2024-12-20 09:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='image'),
        ),
    ]
