# Generated by Django 4.2.17 on 2024-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
